spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: ['httptrace', 'metrics','env','logfile','health']
halo:
  download-timeout: 5m

application:
  version: ${version}
